apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: daemonsets.keti.migration
spec:
  group: keti.migration
  names:
    kind: DaemonSet
    listKind: DaemonSetList
    plural: daemonsets
    singular: daemonset
    shortNames:
      - mds
      - mdaemonset
      - mdaemon
      - mdae
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: DaemonSet is the Schema for the daemonsets API
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
