apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secrets.keti.migration
spec:
  group: keti.migration
  names:
    kind: Secret
    listKind: SecretList
    plural: secrets
    singular: secret
    shortNames:
      - msecret
      - msrt
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Pod is the Schema for the pods API
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        Data:
          type: object
        StringData:
          type: object
        Type:
          type: string
      type: object
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
