apiVersion: keti.migration/v1
kind: Action
metadata:
  name: example-action
spec:
  purpose: migration
  node: cloudedge2-worker2
  podname: pod-test
  destinationnode: cloudedge2-worker1
  namespace: default