apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: controllerrevisions.keti.migration
spec:
  group: keti.migration
  names:
    kind: ControllerRevision
    listKind: ControllerRevisionList
    plural: controllerrevisions
    singular: controllerrevision
    shortNames:
      - mcrv
      - mcontrol
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        Data:
          type: object
        Revision:
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true