apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: statefulsets.keti.migration
spec:
  group: keti.migration
  names:
    kind: StatefulSet
    listKind: StatefulSetList
    plural: statefulsets
    singular: statefulset
    shortNames:
      - msts
      - mstatefulsets
      - mstate
      - mstatefulset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: StatefulSet is the Schema for the statefulsets API
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
