apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configmaps.keti.migration
spec:
  group: keti.migration
  names:
    kind: Configmap
    listKind: ConfigmapList
    plural: configmaps
    singular: configmap
    shortNames:
      - mcm
      - mconfigmap
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Pod is the Schema for the pods API
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        Data:
          type: object
        BinaryData:
          type: object
      type: object
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
