apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: replicasets.keti.migration
spec:
  group: keti.migration
  names:
    kind: ReplicaSet
    listKind: ReplicaSetList
    plural: replicasets
    singular: replicaset
    shortNames:
      - mrs
      - mreplicasets
      - mrep
      - mreplicaset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ReplicaSet is the Schema for the replicasets API
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          description: ReplicaSetSpec defines the desired state of ReplicaSet
          type: object
        status:
          description: ReplicaSetStatus defines the observed state of ReplicaSet
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
