apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployments.keti.migration
spec:
  group: keti.migration
  names:
    kind: Deployment
    listKind: DeploymentList
    plural: deployments
    singular: deployment
    shortNames:
      - mdp
      - mdeployment
      - mdeploy
      - mdep
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Deployment is the Schema for the deployments API
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          description: DeploymentSpec defines the desired state of Deployment
          type: object
        status:
          description: DeploymentStatus defines the observed state of Deployment
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
