apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-managers
spec:
  replicas: 1
  selector:
    matchLabels:
      name: migration-managers
  template:
    metadata:
      labels:
        name: migration-managers
    spec:
      serviceAccountName: migration-manager
      containers:
        - name: migration-manager
          # Replace this with the built image name
          image: hth0919/migration-manager:v0.0.1
          command:
          - migration-manager
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "migration-manager"
