kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: migration-manager
subjects:
  - kind: ServiceAccount
    name: migration-manager
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: migration-manager
  apiGroup: rbac.authorization.k8s.io
